config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  devise_scope :admin do
    get 'admin', to: 'devise/sessions#new'
  end
  resources :posts
  resources :comments
  root to: 'posts#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :admin
  has_many :comments

  validates :title, presence: true
  validates :body, presence: true

  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :username
      devise_parameter_sanitizer.for(:account_update) << :username
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:comment][:post_id])
    @comment = post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.valid?
      @comment.save
      flash[:notice] = "Successfully created comment"
      redirect_to :back
    else
      flash.now[:danger] = "Unable to create comment. Please try again"
      render 'posts#show'
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.paginate(page: params[:page])
  end

  def new
    if admin_signed_in?
      @post = Post.new
    else
      flash[:error] = "Admin privilege is required to access that page"
      redirect_to root_url
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Successfully created a new post"
      redirect_to @post
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.all.order('created_at DESC')
    @comment = @post.comments.build
  end

  def edit
    if admin_signed_in?
      @post = Post.find(params[:id])
    else
      flash[:error] = "Admin privilege is required to access that page"
      redirect_to root_url
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
      flash[:notice] = "Successfully updated post"
    else
      render :edit
    end
  end

  def destroy
    if admin_signed_in?
      @post = Post.find(params[:id])
      @post.destroy
      flash[:notice] = "Successfully deleted post"
      redirect_to posts_path
    else
      flash[:error] = "Admin privilege is required to access that page"
      redirect_to root_url
    end
  end

  private

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "Ronald's Blog"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <span class="content"><%= comment.content %></span>
  <span class="text-muted">Submitted by <%= comment.user.username %></span>
</div>
<hr>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class="sidebar-brand">
  <%= link_to 'MyBlog', root_url %>
</li>
<li><%= link_to 'About Me' %></li>
<li><%= link_to 'Contact Me' %></li>
<% if admin_signed_in? %>
  <hr>
  <li><%= link_to "Sign out", destroy_admin_session_path, method: :delete %></li>
<% end %>

app/views/layouts/_sidebar_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <%= render 'layouts/navigation_links' %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Blog" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/sidebar_navigation' %>
    <div id="main-wrapper">
      <div id="header">
        <% if current_page?(root_path) %>
          <p>All Posts</p>
        <% else %>
          <%= link_to 'Back to all posts', root_url %>
        <% end %>
        <div class="buttons">
          <% if user_signed_in? %>
            <p>Welcome, <%= current_user.username %></p>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'button' %>
            <%= link_to "My Account", edit_user_registration_path, class: 'button' %>
          <% else %>
            <%= link_to 'Sign Up', new_user_registration_path, class: 'button' %>
          <% end %>
        </div>
      </div>
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control tinymce', rows: 20 %>
  </div>
  <%= f.submit 'Submit', class: 'btn-accent btn-lg' %>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <span class="title"><%= link_to post.title, post_path(post) %></span>
  <span class="timestamp"><%= post.created_at.strftime("%B %-d, %Y") %></span>
</div>

app/views/posts/_posts.html.erb
<% if @posts.any? %>
  <ol class="posts">
    <%= render @posts %>
  </ol>
  <%= will_paginate @posts %>
<% end %>

app/views/posts/edit.html.erb
<div id="edit-post-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>
<%= tinymce %>

app/views/posts/index.html.erb
<div id="posts-wrapper">
  <div class="container">
    LIST OF POSTS GOES HERE
  </div>
</div>

app/views/posts/new.html.erb
<div id="new-post-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>
<%= tinymce %>

app/views/posts/show.html.erb
<div id="post-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="text-muted"><%= @post.title %></h1>
        <hr/>
        <%= @post.body.html_safe %>
      </div>
    </div>
  </div>
</div>
<div id="comments-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>Comments</h2>
        <% if user_signed_in? %>
          <a href="#" id="new_comment_toggle">New Comment</a>
          <%= render 'shared/form_comments' %>
        <% end %>
        <%= render 'shared/comments' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_comments.html.erb
<% if @comments.any? %>
  <div class="comments">
    <%= render @comments %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, 'error') %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form_comments.html.erb
<%= form_for @comment do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.hidden_field :post_id %>

  <div class="form-group">
    <%= f.text_area :content, class: 'form-control', placeholder: 'Enter Comment...', rows: 5 %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>